// GENERATED BY number_generate.go; DO NOT EDIT!

package flows

import "math"


func (a Unsigned8) Greater(b Number) bool {
	return a > b.(Unsigned8);
}
func (a Unsigned8) ToInt() int64 {
	return int64(a);
}
func (a Unsigned8) Add(b Number) Number {
	return a + b.(Unsigned8);
}
func (a Unsigned8) Less(b Number) bool {
	return a < b.(Unsigned8);
}
func (a Unsigned8) ToUint() uint64 {
	return uint64(a);
}
func (a Unsigned8) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Unsigned8) ToFloat() float64 {
	return float64(a);
}
func (a Unsigned16) Greater(b Number) bool {
	return a > b.(Unsigned16);
}
func (a Unsigned16) ToInt() int64 {
	return int64(a);
}
func (a Unsigned16) Add(b Number) Number {
	return a + b.(Unsigned16);
}
func (a Unsigned16) Less(b Number) bool {
	return a < b.(Unsigned16);
}
func (a Unsigned16) ToUint() uint64 {
	return uint64(a);
}
func (a Unsigned16) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Unsigned16) ToFloat() float64 {
	return float64(a);
}
func (a Signed8) Greater(b Number) bool {
	return a > b.(Signed8);
}
func (a Signed8) ToInt() int64 {
	return int64(a);
}
func (a Signed8) Add(b Number) Number {
	return a + b.(Signed8);
}
func (a Signed8) Less(b Number) bool {
	return a < b.(Signed8);
}
func (a Signed8) ToUint() uint64 {
	return uint64(a);
}
func (a Signed8) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Signed8) ToFloat() float64 {
	return float64(a);
}
func (a Float64) Greater(b Number) bool {
	return a > b.(Float64);
}
func (a Float64) ToInt() int64 {
	return int64(a);
}
func (a Float64) Add(b Number) Number {
	return a + b.(Float64);
}
func (a Float64) Less(b Number) bool {
	return a < b.(Float64);
}
func (a Float64) ToUint() uint64 {
	return uint64(a);
}
func (a Float64) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Float64) ToFloat() float64 {
	return float64(a);
}
func (a Unsigned32) Greater(b Number) bool {
	return a > b.(Unsigned32);
}
func (a Unsigned32) ToInt() int64 {
	return int64(a);
}
func (a Unsigned32) Add(b Number) Number {
	return a + b.(Unsigned32);
}
func (a Unsigned32) Less(b Number) bool {
	return a < b.(Unsigned32);
}
func (a Unsigned32) ToUint() uint64 {
	return uint64(a);
}
func (a Unsigned32) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Unsigned32) ToFloat() float64 {
	return float64(a);
}
func (a Signed16) Greater(b Number) bool {
	return a > b.(Signed16);
}
func (a Signed16) ToInt() int64 {
	return int64(a);
}
func (a Signed16) Add(b Number) Number {
	return a + b.(Signed16);
}
func (a Signed16) Less(b Number) bool {
	return a < b.(Signed16);
}
func (a Signed16) ToUint() uint64 {
	return uint64(a);
}
func (a Signed16) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Signed16) ToFloat() float64 {
	return float64(a);
}
func (a Signed32) Greater(b Number) bool {
	return a > b.(Signed32);
}
func (a Signed32) ToInt() int64 {
	return int64(a);
}
func (a Signed32) Add(b Number) Number {
	return a + b.(Signed32);
}
func (a Signed32) Less(b Number) bool {
	return a < b.(Signed32);
}
func (a Signed32) ToUint() uint64 {
	return uint64(a);
}
func (a Signed32) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Signed32) ToFloat() float64 {
	return float64(a);
}
func (a Unsigned64) Greater(b Number) bool {
	return a > b.(Unsigned64);
}
func (a Unsigned64) ToInt() int64 {
	return int64(a);
}
func (a Unsigned64) Add(b Number) Number {
	return a + b.(Unsigned64);
}
func (a Unsigned64) Less(b Number) bool {
	return a < b.(Unsigned64);
}
func (a Unsigned64) ToUint() uint64 {
	return uint64(a);
}
func (a Unsigned64) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Unsigned64) ToFloat() float64 {
	return float64(a);
}
func (a Signed64) Greater(b Number) bool {
	return a > b.(Signed64);
}
func (a Signed64) ToInt() int64 {
	return int64(a);
}
func (a Signed64) Add(b Number) Number {
	return a + b.(Signed64);
}
func (a Signed64) Less(b Number) bool {
	return a < b.(Signed64);
}
func (a Signed64) ToUint() uint64 {
	return uint64(a);
}
func (a Signed64) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Signed64) ToFloat() float64 {
	return float64(a);
}
func (a Float32) Greater(b Number) bool {
	return a > b.(Float32);
}
func (a Float32) ToInt() int64 {
	return int64(a);
}
func (a Float32) Add(b Number) Number {
	return a + b.(Float32);
}
func (a Float32) Less(b Number) bool {
	return a < b.(Float32);
}
func (a Float32) ToUint() uint64 {
	return uint64(a);
}
func (a Float32) Log() Number {
	return Float64(math.Log(float64(a)));
}
func (a Float32) ToFloat() float64 {
	return float64(a);
}

